### ISSUE TITLE
Eurodomest issue.

### ISSUE THREAD

**Issue by Torac2** [gregnau/attiny_weather_station#2]
For some reason i cannot open an issue in the Eurodomest part.
I am getting the error connect error: Connection refused (111)

What should i do?
Also can you explain which handle you use in the command char-write-cmd?

root@raspberrypi:~/eurodomest-rgb-blebulb# bash blebulb --set 100
00000100000000000164
connect error: Connection refused (111)

**Comment by gregnau** [comment]
Friend i have no idea, but please do not make issues in other repos.

To be honest, i have already dumped these eurodomest bulbs, since they were completely unreliable. The bluetooth went unresponsive after ~15 minutes after turning it on. Wanted to make a nicer android app also, but whats the point if the bulbs are not possible to control after a few minutes.
